### ISSUE TITLE
Database Init

### ISSUE THREAD

**Issue by satesate-dev** [satesate-dev/go-restful-boilerplate#2]
Database init

**Comment by magazein** [comment]
Hi man, I've created a PR bout this issue, plz kindly review my code, The description bout this issue is lil bit unclear, so kindly comment bout what u really expect

**Comment by magazein** [comment]
Hi, I've commit some changes, actually its my first time using cobra and viper packages, so I'm not really sure bout changes I've made lol, so plz kindly review my code again, thankyou.

**Comment by satesate-dev** [comment]
Did you know about github flow ref: https://guides.github.com/introduction/flow/?
I think you don't use how the github flow is, I will guide you in fast way
- [x] Fork the repository
- [ ] Clone the forked repository (this will be your origin remote repository) 
- [ ] Add `upstream` remote repository to the `upstream` repository which is that was my repository by command
       `
       $ git remote add upstream https://github.com/satesate-dev/go-restful-boilerplate.git
       `
- [ ] On your local PC create new branch before you create a feature example command 
       `$ git checkout -b feat/database-init` mostly I'm using `feat` prefix for a new feature and `fix` prefix for a bug fixing 
- [ ] When you have created a new branch make sure you have pull and rebase by the upstream:master branch by using below following command
      `$ git pull upstream master --rebase`
- [ ] After you have done with guide above then you can write the feature
- [ ] Once you have done with your feature push the code by following command below
      `$ git push origin feat/database-init`

**Comment by magazein** [comment]
yeah i did like you said, the diff is in the forked repository (my repo), I code directly in master branch, I didnt create other branches in the forked repository, thats why the branch i used to PR on your repo is my master branch. but I can change my working branch as you said, let me do it proprly now lol

**Comment by satesate-dev** [comment]
okay I will wait your next PR cheers 🥂

**Comment by magazein** [comment]
thanks for your insight man, really learn a lot from you

**Comment by satesate-dev** [comment]
you're welcome @magazein ✌️
