### ISSUE TITLE
Redis Init

### ISSUE THREAD

**Issue by satesate-dev** [satesate-dev/go-restful-boilerplate#3]

**Comment by magazein** [comment]
Hi, I've created PR for this issue #11, plz review my code sir

**Comment by satesate-dev** [comment]
I’ve reviewed your code LGTM, to night I’ll make a basic api and maybe I’ll create other issue, hope you can help me on the next issue 👌

**Comment by magazein** [comment]
Yeah sure, I'll pick one that I can do🚀
